GET http://localhost:5050/authors

####

GET http://localhost:5050/authors/byid/

####

GET http://localhost:5050/posts/bytitle?title=

####

POST http://localhost:5050/authors/create HTTP/1.1
Content-Type: application/json

{
"firstName": "X",
"lastName": "X",
"email": "emailx@mail.it",
"birthDate": "X",
"password": "X"
}

####
DELETE http://localhost:5050/authors/delete/ HTTP/1.1

####

PATCH  http://localhost:5050/authors/update/
Content-Type: application/json

####

GET http://localhost:5050/posts

####

GET http://localhost:5050/posts/byid/

####

POST http://localhost:5050/posts/create HTTP/1.1
Content-Type: application/json

{
"category": "backend",
"title": "Posttest",
"readTime": {"value":7,"unit":"years"},
"author": {"name":"X"},
"content": "I Love Pizza & Videogames <3"
}

####

PATCH  http://localhost:5050/posts/update/
Content-Type: application/json

####

DELETE http://localhost:5050/posts/delete/ HTTP/1.1


####

GET http://localhost:5050/postId/comments

####

GET http://localhost:5050/postId/comments/CommentId

####

POST http://localhost:5050/postId/add-comment HTTP/1.1
Content-Type: application/json

{
"comm": "Y+",
"rate": 7,
"commAuthor": "Yes!"
}

####
DELETE http://localhost:5050/postId/comments/CommId HTTP/1.1

####

PATCH  http://localhost:5050/postId/comments/CommId
Content-Type: application/json

{
"newComm": "YesYes",
"newRating": 77
}

####
POST http://localhost:5050/send-email HTTP/1.1
Content-Type: application/json

{
  "subject": "email confidenziale",
  "text": "Salve questa è una email."
}


####

POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
  "email": "emailx@mail.it",
  "password": "X"
}

####
